"use strict";const POINTS=[
{id:"asb",n:"Баженовское · Ураласбест",c:"quarry",p:[57.01,61.46],r:"Свердловская обл.",d:"ПАО «Ураласбест». Один из крупнейших действующих поставщиков НСМ в Тюменскую область и ХМАО.",m:"2025: Тюменская область ~1,70 млн т; ХМАО ~272,9 тыс. т. До 6 млн т щебня/год; развитая ж/д отгрузка.",u:"https://www.uralasbest.ru/production/sheben"},
{id:"urd",n:"Чернореченское · Уралдоломит",c:"quarry",p:[56.97,59.82],r:"Свердловская обл.",d:"Действующий карьер доломитового щебня ТД «Уралдоломит».",m:"Станция отгрузки: Билимбай. В 2025 — крупные фактические поставки в Тюменскую область/ХМАО/ЯНАО.",u:"https://uraldolomit.ru"},
{id:"pol",n:"Полуночное-1",c:"quarry",p:[60.87,60.42],r:"Свердловская обл.",d:"Габбро-диабазовый щебень; действующая ж/д отгрузка.",m:"Станции: Ивдель-1, Полуночное. В 2025 зафиксированы поставки получателям Тюменской области/ХМАО/ЯНАО.",u:"https://brokenstone.ru/supplier/245/"},
{id:"sdk",n:"Сангалыкский · ННК",c:"quarry",p:[54.485,59.500],r:"Башкортостан",d:"Сангалыкский диоритовый карьер ННК. Габбро-диорит М1400; авто и ж/д.",m:"Станция Шартымка, ЕСР 805406. Действующий крупный производитель; включён как коммерческий кандидат для северных маршрутов.",u:"https://nnk.ru/quarries-map/178/"},
{id:"emz",n:"Еманжелинский карьер",c:"quarry",p:[54.75,61.32],r:"Челябинская обл.",d:"Действующий производитель андезитового щебня М1200.",m:"Ж/д отгрузка через Еманжелинск; в 2025 зафиксированы поставки в Тюменскую область/ХМАО/ЯНАО.",u:"https://brokenstone.ru/supplier/?id=505"},
{id:"pok",n:"Покровск-Уральский",c:"quarry",p:[60.155068,59.811898],r:"Свердловская обл.",d:"Станция открыта для грузовых операций на путях ООО «Уральский щебень».",m:"ЕСР 775802. Потенциальный источник маршрутных поставок на север.",u:"https://online.freicon.ru/info/stations/775802"},
{id:"tyu",n:"Тюмень",c:"port",p:[57.152,65.527],r:"Тюменская область",d:"Ключевой железнодорожный узел входа в Западную Сибирь.",m:"Используется как промежуточный узел графа; точный тарифный километраж до конкретной станции отправления считать по ЕСР.",u:"https://online.freicon.ru/info"},
{id:"tob",n:"Тобольск",c:"port",p:[58.198,68.254],r:"Тюменская область",d:"Железнодорожный узел северного направления.",m:"Промежуточный узел для детализации коридора Урал → Сургут → ЯНАО.",u:"https://online.freicon.ru/info"},
{id:"surg",n:"Сургут",c:"terminal",p:[61.29020691,73.32350922],r:"ХМАО",d:"Действующая станция Свердловской ж.д.; принимает грузы на путях необщего пользования.",m:"ЕСР 797303. ТР-4. От Сургута до Сургут-Порта по линии — 15 км.",u:"https://online.freicon.ru/info/stations/797303"},
{id:"sport",n:"Сургут-Порт",c:"port",p:[61.25816727,73.26463318],r:"ХМАО",d:"Действующая грузовая станция на окончании ветки Сургут—Сургут-Порт.",m:"ЕСР 797500. ТР-4: 15 км от узла Сургут.",u:"https://online.freicon.ru/info/stations/797500"},
{id:"noy",n:"Ноябрьск",c:"port",p:[63.201,75.451],r:"ЯНАО",d:"Железнодорожный узел на северном ходе.",m:"Промежуточный узел между Сургутом и Пуровском/Коротчаево.",u:"https://online.freicon.ru/info"},
{id:"pur",n:"Пуровск",c:"terminal",p:[64.981,77.823],r:"ЯНАО",d:"Пуровский терминал и станция на оси Пурпе—Коротчаево.",m:"ТР-4: Пуровск → Коротчаево 122 км. Терминал: 31 га, 10 км путей, фронт 54 вагона.",u:"https://purterminal.ru/arenda_tupika"},
{id:"kor",n:"Коротчаево",c:"terminal",p:[65.93019867,78.177742],r:"ЯНАО",d:"Ключевой узел входа в Новоуренгойский и Ямбургский кластер.",m:"ЕСР 799101. FreiCON: действующая станция; линия Коротчаево—Ямбург 306 км.",u:"https://online.freicon.ru/info/stations/799101"},
{id:"fara",n:"Фарафонтьевская",c:"terminal",p:[66.03,76.99],r:"ЯНАО",d:"ЖД станция/промышленная база западнее Нового Уренгоя.",m:"ТР-4: 49 км от Коротчаево; 257 км до Ямбурга. На базе заявлены 16 путей и реализация щебня.",u:"https://krongs.ru/proizvodstvennye-bazy/"},
{id:"nur",n:"Новый Уренгой",c:"port",p:[66.084,76.681],r:"ЯНАО",d:"Центр Новоуренгойского промышленного кластера.",m:"ТР-4: 70 км от Коротчаево; 236 км до Ямбурга.",u:"https://online.freicon.ru/info"},
{id:"yambst",n:"Ямбург (ЖД)",c:"port",p:[67.902,74.884],r:"ЯНАО",d:"Северный конец линии Коротчаево—Ямбург.",m:"ТР-4: 306 км от Коротчаево.",u:"https://online.freicon.ru/info"},
{id:"harp",n:"Харп",c:"quarry",p:[66.801,65.808],r:"ЯНАО",d:"Локальный каменный кластер у Полярного Урала.",m:"Потенциальное преимущество — короткое плечо к Лабытнанги/Обской.",u:"https://nerudas.ru/karery/karery-shchebnya/karery-granitnogo-shchebnya/ooo-arkticheskaya-nerudnaya-kompaniya"},
{id:"podg",n:"Подгорненское",c:"quarry",p:[66.807,65.835],r:"Харп · ЯНАО",d:"Локальный источник строительного камня у Харпа.",m:"Рабочая точка локальной сырьевой альтернативы; характеристики и свободную мощность проверять по первичным документам.",u:"https://www.geokniga.org/"},
{id:"nyag",n:"Нягарпугольское",c:"quarry",p:[66.70,66.10],r:"Лабытнанги · ЯНАО",d:"Сырьевой DD-объект рядом с Лабытнанги.",m:"Статус добычи и лицензии требует актуальной проверки; не считать подтверждённой мощностью.",u:"https://www.rosnedra.gov.ru/"},
{id:"laby",n:"Лабытнанги",c:"port",p:[66.657,66.388],r:"ЯНАО",d:"Железнодорожный тупиковый узел на Оби и речная перевалка.",m:"Вариант ЖД/карьер → вода → Обская губа.",u:"https://online.freicon.ru/info"},
{id:"ob",n:"Обская",c:"port",p:[66.553,66.541],r:"ЯНАО",d:"Узел линии Обская—Бованенково—Карская.",m:"Западная железнодорожная ось полуострова Ямал.",u:"https://online.freicon.ru/info"},
{id:"south",n:"Южно-Русское НГКМ",c:"demand",p:[67.25,79.85],r:"ЯНАО",d:"Действующее месторождение с продолжающимся строительством инфраструктуры.",m:"Ближайшие проекты включают кустовые площадки и дороги; потенциальный спрос НСМ.",u:"https://zakupki.tochka.com/search/22800337-1/"},
{id:"uren",n:"Уренгойское НГКМ",c:"demand",p:[66.15,77.1],r:"ЯНАО",d:"Крупный действующий газовый кластер.",m:"Коротчаево и Фарафонтьевская — ближайшие крупные железнодорожные входы.",u:"https://energybase.ru/"},
{id:"enya",n:"Ен-Яхинское НГКМ",c:"demand",p:[67.05,76.55],r:"ЯНАО",d:"Продолжающиеся СМР и компрессорная инфраструктура.",m:"Северный кластер спроса.",u:"https://energybase.ru/oil-gas-field/yon-yakhinskoye/tenders"},
{id:"pest",n:"Песцовое НГКМ",c:"demand",p:[66.77,76.35],r:"ЯНАО",d:"Действующий промысловый кластер.",m:"Дорожное обслуживание и дальнейшее обустройство.",u:"https://energybase.ru/"},
{id:"yamb",n:"Ямбургское НГКМ",c:"demand",p:[67.92,74.88],r:"ЯНАО",d:"Крупный северный кластер.",m:"Продолжаются дорожные и инфраструктурные работы.",u:"https://energybase.ru/oil-gas-field/yamburgskoe/tenders"},
{id:"bov",n:"Бованенково / Карская",c:"demand",p:[70.36,68.37],r:"Ямал",d:"Газовый и железнодорожный северный узел.",m:"Доступ по линии Обская—Бованенково.",u:"https://energybase.ru/"},
{id:"khar",n:"Харасавэй",c:"demand",p:[71.18,66.82],r:"Ямал",d:"Северный проектный кластер.",m:"Отдельная сезонная/проектная логистика.",u:"https://energybase.ru/"},
{id:"tamb",n:"Тамбейский кластер",c:"demand",p:[71.25,71.90],r:"Ямал",d:"Крупная новая стройка у Обской губы.",m:"КГС, сети, дороги, инженерная подготовка и магистральный газопровод.",u:"https://energybase.ru/upstream/gazdobtambey/tenders/epc"}];const ROUTES=[
{a:"asb",b:"tyu",t:"rail",operator:"rzd",lab:"Асбест → Тюмень",km:"306 км",kind:"Железная дорога РЖД",proof:"ТР-4: Асбест—Баженово 36 + Баженово—Богданович 43 + Богданович—Тюмень 227",src:"https://tr4.info/station/793800"},
{a:"urd",b:"tyu",t:"rail",operator:"rzd",lab:"Билимбай → Тюмень",km:"385 км",kind:"Железная дорога РЖД",proof:"ТР-4: Билимбай—Екатеринбург-Сорт. 49 + Екатеринбург-Сорт.—Богданович 109 + Богданович—Тюмень 227",src:"https://tr4.info/tp/780001"},
{a:"pol",b:"tyu",t:"rail",operator:"rzd",lab:"Полуночное → Тюмень",km:"753 км",kind:"Железная дорога РЖД",proof:"ТР-4: Полуночное—Ивдель II 24 + Ивдель II—Серов-Сорт. 132 + Серов-Сорт.—Тюмень 597",src:"https://tr4.info/station/777507"},
{a:"sdk",b:"tyu",t:"rail",operator:"rzd",lab:"Шартымка → Тюмень",km:"603 км",kind:"Железная дорога РЖД",proof:"ТР-4: Шартымка—Полетаево I 147 + Полетаево I—Челябинск-Главный 26 + Челябинск-Главный—Тюмень 430"},
{a:"emz",b:"tyu",t:"rail",operator:"rzd",lab:"Еманжелинск → Тюмень",km:"472 км",kind:"Железная дорога РЖД",proof:"ТР-4: Еманжелинск—Челябинск-Главный 42 + Челябинск-Главный—Тюмень 430",src:"https://tr4.info/tp/800008"},
{a:"pok",b:"tyu",t:"rail",operator:"rzd",lab:"Покровск-Уральский → Тюмень",km:"684 км",kind:"Железная дорога РЖД",proof:"ТР-4: Покровск-Уральский—Серов-Сорт. 87 + Серов-Сорт.—Тюмень 597",src:"https://tr4.info/tp/774706"},
{a:"tyu",b:"tob",t:"rail",operator:"rzd",lab:"Тюмень → Тобольск",km:"229 км",kind:"Железная дорога РЖД",proof:"ТР-4",src:"https://tr4.info/station/790003"},
{a:"tob",b:"surg",t:"rail",operator:"rzd",lab:"Тобольск → Сургут",km:"476 км",kind:"Железная дорога РЖД",proof:"ТР-4"},
{a:"laby",b:"ob",t:"road",lab:"Лабытнанги → Обская",kind:"Автотранспорт",proof:"Локальное плечо; расстояние расчётное"},
{a:"surg",b:"sport",t:"rail",lab:"Сургут → Сургут-Порт",km:"15 км",kind:"Железная дорога",proof:"ТР-4",src:"https://online.freicon.ru/info/stations/797303"},
{a:"surg",b:"noy",t:"rail",operator:"rzd",lab:"Сургут → Ноябрьск II",km:"270 км",kind:"Железная дорога РЖД",proof:"ТР-4"},
{a:"noy",b:"pur",t:"rail",operator:"rzd",lab:"Ноябрьск II → Пуровск",km:"242 км",kind:"Железная дорога РЖД",proof:"ТР-4"},


{a:"pur",b:"kor",t:"rail",operator:"network",lab:"Пуровск → Коротчаево",km:"122 км",kind:"Железная дорога",proof:"Тарифное руководство №4",src:"https://base.garant.ru/74056968/53f89421bbdaf741eb2d1ecc4ddb4c33/"},

{a:"kor",b:"fara",t:"rail",operator:"yrw",lab:"Коротчаево → Фарафонтьевская",km:"49 км",kind:"Железная дорога",proof:"ТР-4 / FreiCON",src:"https://online.freicon.ru/info/stations/799101"},
{a:"fara",b:"nur",t:"rail",operator:"yrw",lab:"Фарафонтьевская → Новый Уренгой",km:"21 км",kind:"Железная дорога",proof:"ТР-4 (70 − 49)",src:"https://base.garant.ru/74056968/53f89421bbdaf741eb2d1ecc4ddb4c33/"},
{a:"nur",b:"yambst",t:"rail",operator:"yrw",lab:"Новый Уренгой → Ямбург",km:"236 км",kind:"Железная дорога",proof:"Тарифное руководство №4",src:"https://base.garant.ru/74056968/53f89421bbdaf741eb2d1ecc4ddb4c33/"},
{a:"kor",b:"yambst",t:"rail",operator:"yrw",lab:"Коротчаево → Ямбург",km:"306 км",kind:"Железная дорога",proof:"ТР-4 / FreiCON",src:"https://online.freicon.ru/info/stations/799101"},
{a:"kor",b:"uren",t:"road",lab:"последняя миля"},
{a:"kor",b:"south",t:"road",lab:"проектное автоплечо — уточнить"},
{a:"podg",b:"laby",t:"road",lab:"Подгорненское → Лабытнанги · короткое местное плечо"},
{a:"nyag",b:"laby",t:"road",lab:"Нягарпугольское → Лабытнанги · локальное плечо, уточнить"},
{a:"ob",b:"bov",t:"rail",lab:"Обская → Бованенково",km:"525 км",kind:"Железная дорога Газпрома",proof:"ПАО «Газпром»: Обская—Бованенково 525 км; до Карской 572 км",src:"https://www.gazprom.ru/projects/obskaya-bovanenkovo/"},
{a:"laby",b:"tamb",t:"water",lab:"Лабытнанги → Тамбей",km:"водное плечо — считать по судовому ходу",kind:"Водный транспорт",proof:"Подтверждён проектный коридор; точное судоходное расстояние требует трассировки",src:"https://energybase.ru/upstream/gazdobtambey/tenders/epc"},
{a:"bov",b:"tamb",t:"hyp",lab:"проектный коридор — не считать готовым"}];

const RZD_TARIFF_KOR={
 asb:{station:"Асбест",esr:"793800",km:1645,base:159204,classCoef:.72,dispatchCoef:1.03,wagon:78006,ton:1130.52,confidence:"high"},
 urd:{station:"Билимбай",esr:"781907",km:1724,base:166193,classCoef:.72,dispatchCoef:1.03,wagon:81430,ton:1180.14,confidence:"high"},
 pol:{station:"Полуночное",esr:"777507",km:2092,base:187918,classCoef:.70,dispatchCoef:1.01,wagon:87779,ton:1272.16,confidence:"high"},
 sdk:{station:"Шартымка",esr:"805406",km:1942,base:null,classCoef:null,dispatchCoef:null,wagon:null,ton:null,confidence:"distance-verified"},
 emz:{station:"Еманжелинск",esr:"804600",km:1811,base:174652,classCoef:.71,dispatchCoef:1.03,wagon:84386,ton:1222.99,confidence:"high"},
 pok:{station:"Покровск-Уральский",esr:"775802",km:2023,base:187918,classCoef:.70,dispatchCoef:1.01,wagon:87779,ton:1272.16,confidence:"high"}
};
const RZD_TARIFF_META={loadT:69,scheme:"8",etsng:"231–236",cargoCoef:.77,nsmWagonCoef:.909,ownGondolaCoef:.9346,targetSurcharge:1.01,asOf:"30.09.2026",source:"ФАС №894/25; ФАС №88/26; ТР №4"};
const COLORS={demand:"#ff9f43",terminal:"#20c7e8",quarry:"#48c774",port:"#4d86ff"},state={origin:null,destination:null,path:null,rates:{rail:null,yrw:null,road:12,water:4,handling:250},rail:{etsng:"231",cargo:"Минерально-строительные материалы",tariffClass:1,cargoCoef:.77,wagonCoef:.909,source:"ФАС №894/25 · ТР №1 (ред. 03.08.2026)"}};
const byId=new Map(POINTS.map(p=>[p.id,p])),adj=new Map(POINTS.map(p=>[p.id,[]])),markers=new Map(),lines=[];
ROUTES.forEach((r,i)=>{r.status=r.status||(r.t==="hyp"?"hypothesis":(r.km&&/^\d/.test(r.km)?"verified":"corridor"));if(r.t!=="hyp"&&r.status!=="hypothesis"&&!(r.a==="kor"&&r.b==="yambst")){adj.get(r.a)?.push([r.b,i]);adj.get(r.b)?.push([r.a,i])}});
const origin=document.querySelector("#origin"),destination=document.querySelector("#destination"),hint=document.querySelector("#hint"),result=document.querySelector("#result"),detail=document.querySelector("#detail");

if(typeof window.L==="undefined"){
  hint.textContent="Карта не загрузилась: недоступна библиотека Leaflet.";
  document.querySelector("#map").innerHTML='<div class="map-error">Картографическая библиотека недоступна.<br>Список карьеров и данные доступны ниже.</div>';
  throw new Error("Leaflet unavailable");
}
const map=L.map("map",{zoomControl:false}).setView([66,72],5);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);L.control.zoom({position:"bottomright"}).addTo(map);

function icon(p){return L.divIcon({className:"point-wrap",html:'<div class="map-point" style="--c:'+COLORS[p.c]+'"></div>',iconSize:[16,16],iconAnchor:[8,8]})}
POINTS.forEach(p=>{const m=L.marker(p.p,{icon:icon(p)}).bindTooltip(p.n,{permanent:true,direction:"top",className:"point-label",offset:[0,-8]});m.on("click",()=>onPoint(p));m.addTo(map);markers.set(p.id,m)});
function style(r){if(r.status==="hypothesis")return{color:"#9a7474",weight:1,dashArray:"3 7",opacity:.2};if(r.t==="road")return{color:"#92765e",weight:1.2,opacity:.3};if(r.t==="water")return{color:"#4b83aa",weight:1.3,opacity:.34};if(r.operator==="yrw")return{color:"#756d8d",weight:1.3,opacity:.36};return{color:"#66757d",weight:1.2,opacity:.32}}
ROUTES.forEach((r,i)=>{const a=byId.get(r.a),b=byId.get(r.b);if(!a||!b)return;const l=L.polyline([a.p,b.p],{...style(r),lineCap:"round",lineJoin:"round",interactive:false}).addTo(map);l.edgeIndex=i;lines.push(l)});
POINTS.filter(p=>p.c==="quarry").forEach(p=>origin.add(new Option(p.n,p.id)));
function reach(id){const seen=new Set([id]),q=[id];while(q.length){const x=q.shift();for(const [y] of adj.get(x)||[])if(!seen.has(y)){seen.add(y);q.push(y)}}return seen}
function setA(id){state.origin=id;state.destination=null;state.path=null;origin.value=id;const rr=reach(id);destination.innerHTML='<option value="">Выберите B</option>';POINTS.filter(p=>p.id!==id&&p.c!=="quarry"&&rr.has(p.id)).forEach(p=>destination.add(new Option(p.n,p.id)));destination.disabled=false;hint.textContent="A выбран. Нажмите на доступную B.";result.hidden=true;render()}
function setB(id){if(!state.origin)return;state.destination=id;destination.value=id;calc()}
function onPoint(p){if(p.c==="quarry")setA(p.id);else if(state.origin&&[...destination.options].some(o=>o.value===p.id))setB(p.id);show(p)}
function show(p){detail.hidden=false;detail.innerHTML='<button class="close">×</button><h2>'+p.n+'</h2><div class="region">'+p.r+'</div><p>'+p.d+'</p><div class="evidence">'+p.m+'</div><div class="role">'+(p.c==="quarry"?"Точка A":state.destination===p.id?"Точка B":"Объект")+'</div><p><a target="_blank" rel="noopener" href="'+p.u+'">Источник ↗</a></p>';detail.querySelector(".close").onclick=()=>detail.hidden=true}
function path(a,b){const q=[a],prev=new Map([[a,null]]),pe=new Map();while(q.length){const x=q.shift();if(x===b)break;for(const [y,i] of adj.get(x)||[])if(!prev.has(y)){prev.set(y,x);pe.set(y,i);q.push(y)}}if(!prev.has(b))return null;let x=b,ids=[],edges=[];while(x!==a){ids.push(x);edges.push(pe.get(x));x=prev.get(x)}ids.push(a);return{ids:ids.reverse(),edges:edges.reverse()}}
function geo(a,b){const A=byId.get(a).p,B=byId.get(b).p,R=6371,d=Math.PI/180,z=Math.sin((B[0]-A[0])*d/2)**2+Math.cos(A[0]*d)*Math.cos(B[0]*d)*Math.sin((B[1]-A[1])*d/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
function dist(r){if(r.km&&/^\d/.test(r.km))return{km:parseFloat(r.km),exact:true};return{km:Math.round(geo(r.a,r.b)*(r.t==="road"?1.22:r.t==="rail"?1.14:r.t==="water"?1.08:1.15)),exact:false}}
function mk(r){return r.operator==="yrw"?"yrw":r.t}function mn(r){return r.operator==="yrw"?"ЯЖДК":r.t==="rail"?"ЖД":r.t==="road"?"Авто":r.t==="water"?"Вода":"Коридор"}
function calc(){const p=path(state.origin,state.destination);if(!p){hint.textContent="Нет рабочего маршрута без гипотез.";return}state.path=p;let km=0,sum=0,est=0,tr=0,last=null;const legs=p.edges.map(i=>{const r=ROUTES[i],d=dist(r),m=mk(r),rate=state.rates[m],priced=Number.isFinite(rate)&&rate>0,c=priced?d.km*rate:0;km+=d.km;if(priced)sum+=c;if(!d.exact)est+=d.km;if(last&&last!==m)tr++;last=m;return{r,d,rate,c,priced}});const hand=tr*state.rates.handling;sum+=hand;const unpriced=legs.filter(x=>!x.priced);result.hidden=false;result.innerHTML='<div class="summary"><div class="kpi"><small>Всего</small><strong>'+(est?"≈ ":"")+Math.round(km)+' км</strong></div><div class="kpi"><small>Доставка</small><strong>'+(unpriced.length?'нужен тариф':'≈ '+Math.round(sum).toLocaleString("ru-RU")+' ₽/т')+'</strong></div><div class="kpi"><small>Эфф. тариф</small><strong>'+(unpriced.length?'—':'≈ '+(sum/km).toFixed(1).replace(".",",")+' ₽/т·км')+'</strong></div></div>'+(unpriced.length?'<div class="handling"><b>Стоимость не рассчитана:</b> для ЖД/ЯЖДК нет подтверждённой ставки. Введите коммерческую ставку вручную либо используйте тарифный расчёт по действующему Тарифному руководству №1.</div>':'')+'<div class="legs">'+legs.map((x,n)=>'<div class="leg"><div><b>'+(n+1)+'. '+mn(x.r)+' · '+byId.get(x.r.a).n+' → '+byId.get(x.r.b).n+'</b><small>'+(x.d.exact?"заданное":"≈ расчётное")+(x.r.proof?" · "+x.r.proof:"")+'</small></div><div class="money"><b>'+(x.d.exact?"":"≈ ")+x.d.km+' км</b><small>'+x.rate+' ₽/т·км</small><strong>≈ '+Math.round(x.c).toLocaleString("ru-RU")+' ₽/т</strong></div></div>').join("")+'</div>'+(tr?'<div class="handling">Перевалки: '+tr+' × '+state.rates.handling+' = <b>'+hand+' ₽/т</b></div>':'')+'<div class="confidence"><b>Достоверность: '+(est===0?"высокая":est/km<.35?"средняя":"предварительная")+'</b> · расчётных км: '+Math.round(est)+'</div><div class="rates">'+ri("rail","ЖД")+ri("yrw","ЯЖДК")+ri("road","Авто")+ri("water","Вода")+ri("handling","Перевалка")+'</div><div class="note">ЖД/ЯЖДК: ставка по умолчанию удалена. Для коммерческого расчёта нужна подтверждённая ставка/тарифный расчёт. Авто, вода и перевалка пока сценарные. Материал в карьере не включён.</div>';if(state.destination==="kor"){const q=RZD_TARIFF_KOR[state.origin],box=document.createElement("div");box.className="handling";box.innerHTML=q?'<b>Регулируемый тариф РЖД · '+RZD_TARIFF_META.asOf+'</b><br>'+q.station+' (ЕСР '+q.esr+') → Коротчаево: <b>'+q.km+' тарифных км</b><br>Схема №8, 69 т: '+q.base.toLocaleString("ru-RU")+' ₽/вагон × '+q.classCoef+' × 0,77 × 0,909 × 0,9346 × '+q.dispatchCoef+' × 1,01.<br><strong>'+q.wagon.toLocaleString("ru-RU")+' ₽/вагон · '+q.ton.toLocaleString("ru-RU",{maximumFractionDigits:2})+' ₽/т</strong><br><small>Только регулируемый тариф инфраструктуры РЖД. ЯЖДК, Газпром, авто/вода и терминальные услуги не включены.</small>':'<b>РЖД-тариф удержан:</b> тарифное расстояние этой станции ещё проходит независимую сверку.';result.prepend(box);}
result.querySelectorAll("[data-rate]").forEach(e=>e.onchange=()=>{state.rates[e.dataset.rate]=e.value.trim()===""?null:(+e.value||null);calc()});hint.textContent="Маршрут рассчитан.";render();map.fitBounds(L.latLngBounds(p.ids.map(id=>byId.get(id).p)),{paddingTopLeft:[30,150],paddingBottomRight:[30,260]})}
function ri(k,n){return'<label>'+n+(k==="handling"?" ₽/т":" ₽/т·км")+'<input data-rate="'+k+'" inputmode="decimal" value="'+(state.rates[k]??'')+'" placeholder="'+(k==='rail'||k==='yrw'?'введите ставку':'')+'"></label>'}
function render(){markers.forEach((m,id)=>{const e=m.getElement()?.querySelector(".map-point");if(e){e.classList.toggle("selected-a",id===state.origin);e.classList.remove("available-b")}});if(state.origin){const ok=new Set([...destination.options].map(o=>o.value));markers.forEach((m,id)=>{if(ok.has(id))m.getElement()?.querySelector(".map-point")?.classList.add("available-b")})}lines.forEach(l=>l.setStyle(style(ROUTES[l.edgeIndex])));if(state.path)state.path.edges.forEach(i=>lines.find(l=>l.edgeIndex===i)?.setStyle({color:"#0c668f",weight:4,opacity:.95,dashArray:null}))}
function fit(){map.fitBounds(L.latLngBounds(POINTS.filter(p=>["podg","nyag","laby","ob","kor","bov","tamb"].includes(p.id)).map(p=>p.p)),{paddingTopLeft:[30,140],paddingBottomRight:[30,140]})}
origin.onchange=()=>origin.value&&setA(origin.value);destination.onchange=()=>destination.value&&setB(destination.value);document.querySelector("#fit").onclick=fit;document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));POINTS.forEach(p=>{const m=markers.get(p.id),show=b.dataset.filter==="all"||p.c===b.dataset.filter;if(show&&!map.hasLayer(m))m.addTo(map);if(!show&&map.hasLayer(m))map.removeLayer(m)})});fit();render();