"use strict";const POINTS=[
{id:"asb",n:"Баженовское · Ураласбест",c:"quarry",p:[57.01,61.46],r:"Свердловская обл.",d:"ПАО «Ураласбест». Один из крупнейших действующих поставщиков НСМ в Тюменскую область и ХМАО.",m:"2025: Тюменская область ~1,70 млн т; ХМАО ~272,9 тыс. т. До 6 млн т щебня/год; развитая ж/д отгрузка.",u:"https://www.uralasbest.ru/production/sheben"},
{id:"urd",n:"Чернореченское · Уралдоломит",c:"quarry",p:[56.97,59.82],r:"Свердловская обл.",d:"Действующий карьер доломитового щебня ТД «Уралдоломит».",m:"Станция отгрузки: Билимбай. В 2025 — крупные фактические поставки в Тюменскую область/ХМАО/ЯНАО.",u:"https://uraldolomit.ru"},
{id:"pol",n:"Полуночное-1",c:"quarry",p:[60.87,60.42],r:"Свердловская обл.",d:"Габбро-диабазовый щебень; действующая ж/д отгрузка.",m:"Станции: Ивдель-1, Полуночное. В 2025 зафиксированы поставки получателям Тюменской области/ХМАО/ЯНАО.",u:"https://brokenstone.ru/supplier/245/"},
{id:"sdk",n:"Сангалыкский · ННК",c:"quarry",group:"nnk",p:[54.485,59.500],r:"Башкортостан",d:"Сангалыкский диоритовый карьер ННК. Габбро-диорит М1400; авто и ж/д.",m:"Станция Шартымка, ЕСР 805406. Действующий крупный производитель; включён как коммерческий кандидат для северных маршрутов.",u:"https://nnk.ru/quarries-map/178/"},
{id:"emz",n:"Еманжелинский карьер",c:"quarry",p:[54.75,61.32],r:"Челябинская обл.",d:"Действующий производитель андезитового щебня М1200.",m:"Ж/д отгрузка через Еманжелинск; в 2025 зафиксированы поставки в Тюменскую область/ХМАО/ЯНАО.",u:"https://brokenstone.ru/supplier/?id=505"},
{id:"pok",n:"Покровск-Уральский",c:"quarry",p:[60.155068,59.811898],r:"Свердловская обл.",d:"Станция открыта для грузовых операций на путях ООО «Уральский щебень».",m:"ЕСР 775802. Потенциальный источник маршрутных поставок на север.",u:"https://online.freicon.ru/info/stations/775802"},
{id:"nkukam",n:"Каменный карьер · ННК",c:"quarry",group:"nnk",p:[55.10,83.30],r:"Тогучинский район · Новосибирская обл.",d:"Действующий карьер АО «Новосибирское карьероуправление»/ННК. Альбитофир и диабаз; щебень М1400, F300, включая крупные фракции и бутовый камень.",m:"Сильный западносибирский кандидат для нефтегазовой инфраструктуры. НКУ прямо называет «Роснефть» и «Газпром» среди клиентов и фиксирует стабильные отгрузки для нужд «Роснефти» с 2006 года. Конкретные НГКМ в открытом источнике не раскрыты.",u:"https://nkuoao.ru/about/"},
{id:"medv",n:"Медведский карьер · ННК",c:"quarry",group:"nnk",p:[54.15,83.45],r:"Черепановский район · Новосибирская обл.",d:"Диабазовые и базальтовые/андезито-базальтовые порфириты. Щебень М1400, F300; 5–20, 20–40, 20–70, 40–70 мм, ЩПС; в отраслевом каталоге указан бутовый камень. Авто и ЖД.",m:"Продукция высокой прочности и морозостойкости; декларации 2026 подтверждают дорожные фракции. НКУ имеет подтверждённую историю поставок для «Роснефти» и «Газпрома», но привязка именно Медведского карьера к конкретному месторождению требует накладных/реестра вагонов.",u:"https://www.brokenstone.ru/supplier/?id=737"},
{id:"novob",n:"Новобибеевский карьер · ННК",c:"quarry",group:"nnk",p:[55.18,84.08],r:"Болотнинский район · Новосибирская обл.",d:"Гранитный строительный камень. Щебень М1200–1400, F300, И1. Отгрузка автомобильным и водным транспортом.",m:"Интересен как источник прочного морозостойкого гранитного щебня с выходом к бассейну Оби. НКУ поставляет материалы нефтегазовым компаниям, однако отдельный кейс Новобибеево → конкретное НГКМ в открытых источниках пока не подтверждён.",u:"https://sqltd.ru/partner/oao-novosibirskoe-kareroupravlenie-shheben-v-novosibirske-cena/"},
{id:"shay",n:"Шайдуровский карьер · ННК",c:"quarry",group:"nnk",p:[54.021933,81.807141],r:"Сузунский район · Новосибирская обл.",d:"Базальтовый порфирит и альбитофир. М1200–1400, F200–300; щебень 5–20, 20–40, 40–70 и ЩПС. Декларация 2026 подтверждает дорожный щебень.",m:"Технически подходит для тяжёлых дорожных оснований и площадок. Сейчас ЖД-доставка с карьера отсутствует, поэтому северное плечо требует отдельной логистической схемы.",u:"https://www.nnk.ru/quarries-map/21370/"},
{id:"baran",n:"Баранцевское",c:"quarry",group:"independent",p:[56.560029,86.072676],r:"Томский район · Томская обл.",d:"Одно из двух месторождений высокопрочного строительного камня Томской области. Кератофир/высокопрочный камень: М1400; актуальные каталоги указывают F300–F400. Фракции 5–20, 20–40, 40–70, 70–120 и крупнее; исторически — также бутовый камень.",m:"Очень сильный локальный кандидат для нефтегазовой Томской области и дальнейшего северного плеча: минимизирует завоз высокопрочного камня из других субъектов. Факт поставки на конкретное НГКМ пока не найден — статус «перспективный источник», не подтверждённый кейс.",u:"https://nerudas.ru/karery/karery-shchebnya/karery-granitnogo-shchebnya/barantsevskij"},
{id:"tyagun",n:"Тягунский механизированный карьер",c:"quarry",group:"independent",p:[53.85,85.55],r:"Заринский район · Алтайский край",d:"Порфирит и диабаз. Высокопрочный щебень М1400, F300, лещадность I группы. Производительность до 1,5 млн т/год; отгрузка до 50 вагонов в сутки.",m:"Крупный железнодорожный источник прочного морозостойкого камня Западной Сибири. Технически интересен для северных маршрутных отправок; доказанный кейс поставки на конкретное НГКМ пока не найден.",u:"https://www.stone22.ru/"},
{id:"malet",n:"Малетинский / Плотинный · Алтайские карьеры",c:"quarry",group:"altai",p:[53.79,81.35],r:"Алтайский край",d:"Туфопесчаник; щебень М1200, F300, фракции 5–20, 20–40, 40–70; в отраслевом каталоге присутствует бутовый камень. Холдинг развивает также речную логистику по Оби.",m:"Перспективен как южный западносибирский источник с мультимодальной логистикой. Производственная база подтверждена, но поставку именно на нефтегазовое месторождение пока не считаем доказанной.",u:"https://brokenstone.ru/supplier/?id=734"},
{id:"mitr",n:"Митрофановское · кварцевый порфир",c:"quarry",group:"independent",p:[55.72,84.93],r:"Кемеровская обл. · Юргинский район",d:"Независимый источник кварцевого порфира. Заявлены М1400, F300 и бутовый камень; производитель предлагает повагонные и маршрутные отправки, включая направление Сургут/ХМАО.",m:"До станции Юрга заявлено около 45 км автоплеча. Точное примыкание, паспорт качества и фактическую экономику северного маршрута проверять в DD.",u:"https://porfir42.ru/"},
{id:"arty",n:"Артыштинское · актив на продажу",c:"quarry",group:"potential",p:[54.16,86.30],r:"Кемеровская обл.",d:"Потенциальный acquisition target: в объявлении 2026 заявлен щебёночный карьер Артыштинского месторождения, высокопрочный известняк М1000.",m:"Заявлены запасы около 4,63 млн м³ / 10,19 млн т и лицензия до 2034 года. Ярко-оранжевый статус означает «требует полного DD»: собственник, лицензия, качество, инфраструктура и ЖД должны быть подтверждены первичными документами.",u:"https://www.biztotal.ru/prodazha_biznesa/mestorozdenia-kar-ery.html?page=1"},
{id:"tyu",n:"Тюмень",c:"port",p:[57.152,65.527],r:"Тюменская область",d:"Ключевой железнодорожный узел входа в Западную Сибирь.",m:"Используется как промежуточный узел графа; точный тарифный километраж до конкретной станции отправления считать по ЕСР.",u:"https://online.freicon.ru/info"},
{id:"tob",n:"Тобольск",c:"port",p:[58.198,68.254],r:"Тюменская область",d:"Железнодорожный узел северного направления.",m:"Промежуточный узел для детализации коридора Урал → Сургут → ЯНАО.",u:"https://online.freicon.ru/info"},
{id:"surg",n:"Сургут",c:"terminal",p:[61.29020691,73.32350922],r:"ХМАО",d:"Действующая станция Свердловской ж.д.; принимает грузы на путях необщего пользования.",m:"ЕСР 797303. ТР-4. От Сургута до Сургут-Порта по линии — 15 км.",u:"https://online.freicon.ru/info/stations/797303"},
{id:"sport",n:"Сургут-Порт",c:"port",p:[61.25816727,73.26463318],r:"ХМАО",d:"Действующая грузовая станция на окончании ветки Сургут—Сургут-Порт.",m:"ЕСР 797500. ТР-4: 15 км от узла Сургут.",u:"https://online.freicon.ru/info/stations/797500"},
{id:"noy",n:"Ноябрьск",c:"port",p:[63.201,75.451],r:"ЯНАО",d:"Железнодорожный узел на северном ходе.",m:"Промежуточный узел между Сургутом и Пуровском/Коротчаево.",u:"https://online.freicon.ru/info"},
{id:"pur",n:"Пуровск",c:"terminal",p:[64.981,77.823],r:"ЯНАО",d:"Пуровский терминал и станция на оси Пурпе—Коротчаево.",m:"ТР-4: Пуровск → Коротчаево 122 км. Терминал: 31 га, 10 км путей, фронт 54 вагона.",u:"https://purterminal.ru/arenda_tupika"},
{id:"kor",n:"Коротчаево",c:"terminal",p:[65.93019867,78.177742],r:"ЯНАО",d:"Ключевой узел входа в Новоуренгойский и Ямбургский кластер.",m:"ЕСР 799101. FreiCON: действующая станция; линия Коротчаево—Ямбург 306 км.",u:"https://online.freicon.ru/info/stations/799101"},
{id:"fara",n:"Фарафонтьевская",c:"terminal",p:[66.03,76.99],r:"ЯНАО",d:"ЖД станция/промышленная база западнее Нового Уренгоя.",m:"ТР-4: 49 км от Коротчаево; 257 км до Ямбурга. На базе заявлены 16 путей и реализация щебня.",u:"https://krongs.ru/proizvodstvennye-bazy/"},
{id:"nur",n:"Новый Уренгой",c:"port",p:[66.084,76.681],r:"ЯНАО",d:"Центр Новоуренгойского промышленного кластера.",m:"ТР-4: 70 км от Коротчаево; 236 км до Ямбурга.",u:"https://online.freicon.ru/info"},
{id:"yambst",n:"Ямбург (ЖД)",c:"port",p:[67.902,74.884],r:"ЯНАО",d:"Северный конец линии Коротчаево—Ямбург.",m:"ТР-4: 306 км от Коротчаево.",u:"https://online.freicon.ru/info"},
{id:"harp",n:"Харп · Арктическая нерудная компания",c:"quarry",group:"independent",p:[66.812811,65.864041],r:"Харп · ЯНАО",d:"Действующий локальный производственный объект ООО «Арктическая нерудная компания» в промзоне Харпа у станции Харп-Северное сияние. Основной профиль — добыча строительного камня; локальная база Полярного Урала.",m:"Статус компании действующий; карьерная площадка актуализирована в 2026. Конкретные марки/фракции щебня и бутового камня подтверждать паспортом партии: открытый источник не даёт достаточной продуктовой спецификации. Близость к Лабытнанги/Обской делает объект стратегическим для западно-ямальской логистики.",u:"https://nerudas.ru/karery/karery-shchebnya/karery-granitnogo-shchebnya/ooo-arkticheskaya-nerudnaya-kompaniya"},
{id:"podg",n:"Подгорненское · Регионгеоресурс",c:"quarry",group:"independent",p:[66.807,65.835],r:"Харп · ЯНАО",d:"Месторождение строительного камня. ООО «Регионгеоресурс»: щебень из горных пород для дорожного строительства; действующая декларация 2025 охватывает основные фракции примерно 4–90 мм и широкие смеси. Ранее декларировались также 70–120 и 120–150 мм.",m:"Сильный локальный кандидат для нефтегазовой стройки ЯНАО: дорожные основания, кустовые площадки и инфраструктурные отсыпки. Производитель действующий. Связь конкретных партий Подгорненского с отдельными НГКМ в открытых данных пока не доказана — не смешивать с общими кейсами поставщиков на месторождения.",u:"https://xn----7sbajahheyaepn1ca0aveqcb0fxl.xn--p1acf/kompaniya/ooo-regiongeoresurs-1138901000083/"},
{id:"nyag",n:"Нягарпугольское",c:"quarry",group:"potential",p:[66.70,66.10],r:"Лабытнанги · ЯНАО",d:"Месторождение плотных горных пород Приуральского района. В открытых реестрах продукции подтверждается щебень для дорожного строительства: смеси 5–20 мм, фракции 20–40 и 40–70 мм.",m:"Локальный западно-сибирский источник рядом с Лабытнанги/Обской. Исторически разработка связывается с ООО «Ямал-Гранит»/«Кентавр»; текущую лицензию, мощность и фактическую доступность объёмов нужно подтвердить перед коммерческим использованием. В карту внесён как DD-кандидат, а не как гарантированная мощность.",u:"https://b2b-postavki.ru/proizvoditel/scheben-frakcii-russia.html"},
{id:"amf",n:"Амфиболитовое",c:"quarry",group:"potential",p:[66.82,65.82],r:"Харп · ЯНАО",d:"Крупное месторождение габброидов/амфиболитов у Харпа; геологическими материалами подтверждена пригодность пород для производства строительного щебня. В статистике поставок отдельно фиксируется бутовый камень месторождения «Амфиболитовое» в направлении Лабытнанги.",m:"Прямо релевантно запросу Aurora по щебню и бутовому камню. Открытые данные фиксируют 3 180 т / 53 вагона бутового камня в направлении Лабытнанги. Текущий недропользователь, действующая производственная мощность и актуальные паспорта качества требуют DD перед контрактованием.",u:"https://brokenstone.ru/supplypromo/"},
{id:"laby",n:"Лабытнанги",c:"port",p:[66.657,66.388],r:"ЯНАО",d:"Железнодорожный тупиковый узел на Оби и речная перевалка.",m:"Вариант ЖД/карьер → вода → Обская губа.",u:"https://online.freicon.ru/info"},
{id:"ob",n:"Обская",c:"port",p:[66.553,66.541],r:"ЯНАО",d:"Узел линии Обская—Бованенково—Карская.",m:"Западная железнодорожная ось полуострова Ямал.",u:"https://online.freicon.ru/info"},
{id:"south",n:"Южно-Русское НГКМ",c:"demand",p:[67.25,79.85],r:"ЯНАО",d:"Действующее месторождение с продолжающимся строительством инфраструктуры.",m:"Ближайшие проекты включают кустовые площадки и дороги; потенциальный спрос НСМ.",u:"https://zakupki.tochka.com/search/22800337-1/"},
{id:"uren",n:"Уренгойское НГКМ",c:"demand",p:[66.15,77.1],r:"ЯНАО",d:"Крупный действующий газовый кластер.",m:"Коротчаево и Фарафонтьевская — ближайшие крупные железнодорожные входы.",u:"https://energybase.ru/"},
{id:"enya",n:"Ен-Яхинское НГКМ",c:"demand",p:[67.05,76.55],r:"ЯНАО",d:"Продолжающиеся СМР и компрессорная инфраструктура.",m:"Северный кластер спроса.",u:"https://energybase.ru/oil-gas-field/yon-yakhinskoye/tenders"},
{id:"pest",n:"Песцовое НГКМ",c:"demand",p:[66.77,76.35],r:"ЯНАО",d:"Действующий промысловый кластер.",m:"Дорожное обслуживание и дальнейшее обустройство.",u:"https://energybase.ru/"},
{id:"yamb",n:"Ямбургское НГКМ",c:"demand",p:[67.92,74.88],r:"ЯНАО",d:"Крупный северный кластер.",m:"Продолжаются дорожные и инфраструктурные работы.",u:"https://energybase.ru/oil-gas-field/yamburgskoe/tenders"},
{id:"bov",n:"Бованенково / Карская",c:"demand",p:[70.36,68.37],r:"Ямал",d:"Газовый и железнодорожный северный узел.",m:"Доступ по линии Обская—Бованенково.",u:"https://energybase.ru/"},
{id:"khar",n:"Харасавэй",c:"demand",p:[71.18,66.82],r:"Ямал",d:"Северный проектный кластер.",m:"Отдельная сезонная/проектная логистика.",u:"https://energybase.ru/"},
{id:"tamb",n:"Тамбейский кластер",c:"demand",p:[71.25,71.90],r:"Ямал",d:"Крупная новая стройка у Обской губы.",m:"КГС, сети, дороги, инженерная подготовка и магистральный газопровод.",u:"https://energybase.ru/upstream/gazdobtambey/tenders/epc"}];const ROUTES=[
{a:"asb",b:"tyu",t:"rail",lab:"Баженовское → Тюмень",kind:"Железная дорога",proof:"Коммерческий ЖД-коридор; тарифное расстояние уточнить по станции отправления/ЕСР"},
{a:"urd",b:"tyu",t:"rail",lab:"Билимбай → Тюмень",kind:"Железная дорога",proof:"ЖД-коридор; тарифное расстояние уточнить по ЕСР"},
{a:"pol",b:"tyu",t:"rail",lab:"Полуночное → Тюмень",kind:"Железная дорога",proof:"ЖД-коридор; тарифное расстояние уточнить по ЕСР"},
{a:"sdk",b:"tyu",t:"rail",lab:"Шартымка → Тюмень",kind:"Железная дорога",proof:"ЖД-коридор; тарифное расстояние уточнить по ЕСР"},
{a:"emz",b:"tyu",t:"rail",lab:"Еманжелинск → Тюмень",kind:"Железная дорога",proof:"ЖД-коридор; тарифное расстояние уточнить по ЕСР"},
{a:"pok",b:"tyu",t:"rail",lab:"Покровск-Уральский → Тюмень",kind:"Железная дорога",proof:"ЖД-коридор; тарифное расстояние уточнить по ЕСР"},
{a:"tyu",b:"tob",t:"rail",lab:"Тюмень → Тобольск",kind:"Железная дорога",proof:"Северный ход Свердловской ЖД; тарифное расстояние уточнить по ЕСР"},
{a:"tob",b:"surg",t:"rail",lab:"Тобольск → Сургут",kind:"Железная дорога",proof:"Северный ход Свердловской ЖД; тарифное расстояние уточнить по ЕСР"},
{a:"laby",b:"ob",t:"road",lab:"Лабытнанги → Обская",kind:"Автотранспорт",proof:"Локальное плечо; расстояние расчётное"},
{a:"surg",b:"sport",t:"rail",lab:"Сургут → Сургут-Порт",km:"15 км",kind:"Железная дорога",proof:"ТР-4",src:"https://online.freicon.ru/info/stations/797303"},
{a:"surg",b:"noy",t:"rail",lab:"Сургут → Ноябрьск",kind:"Железная дорога",proof:"Коридор; тарифное расстояние считать по ЕСР"},
{a:"noy",b:"pur",t:"rail",lab:"Ноябрьск → Пуровск",kind:"Железная дорога",proof:"Коридор; тарифное расстояние считать по ЕСР"},


{a:"pur",b:"kor",t:"rail",operator:"network",lab:"Пуровск → Коротчаево",km:"122 км",kind:"Железная дорога",proof:"Тарифное руководство №4",src:"https://base.garant.ru/74056968/53f89421bbdaf741eb2d1ecc4ddb4c33/"},

{a:"kor",b:"fara",t:"rail",operator:"yrw",lab:"Коротчаево → Фарафонтьевская",km:"49 км",kind:"Железная дорога",proof:"ТР-4 / FreiCON",src:"https://online.freicon.ru/info/stations/799101"},
{a:"fara",b:"nur",t:"rail",operator:"yrw",lab:"Фарафонтьевская → Новый Уренгой",km:"21 км",kind:"Железная дорога",proof:"ТР-4 (70 − 49)",src:"https://base.garant.ru/74056968/53f89421bbdaf741eb2d1ecc4ddb4c33/"},
{a:"nur",b:"yambst",t:"rail",operator:"yrw",lab:"Новый Уренгой → Ямбург",km:"236 км",kind:"Железная дорога",proof:"Тарифное руководство №4",src:"https://base.garant.ru/74056968/53f89421bbdaf741eb2d1ecc4ddb4c33/"},
{a:"kor",b:"yambst",t:"rail",operator:"yrw",lab:"Коротчаево → Ямбург",km:"306 км",kind:"Железная дорога",proof:"ТР-4 / FreiCON",src:"https://online.freicon.ru/info/stations/799101"},
{a:"kor",b:"uren",t:"road",lab:"последняя миля"},
{a:"kor",b:"south",t:"road",lab:"проектное автоплечо — уточнить"},
{a:"podg",b:"laby",t:"road",lab:"Подгорненское → Лабытнанги · короткое местное плечо"},
{a:"harp",b:"laby",t:"road",lab:"Харп · АНК → Лабытнанги · локальное плечо"},
{a:"amf",b:"laby",t:"road",lab:"Амфиболитовое → Лабытнанги · локальное плечо; подтверждён кейс поставки бутового камня в направлении Лабытнанги"},
{a:"nyag",b:"laby",t:"road",lab:"Нягарпугольское → Лабытнанги · локальное плечо, уточнить"},
{a:"ob",b:"bov",t:"rail",lab:"Обская → Бованенково",km:"525 км",kind:"Железная дорога Газпрома",proof:"ПАО «Газпром»: Обская—Бованенково 525 км; до Карской 572 км",src:"https://www.gazprom.ru/projects/obskaya-bovanenkovo/"},
{a:"laby",b:"tamb",t:"water",lab:"Лабытнанги → Тамбей",km:"водное плечо — считать по судовому ходу",kind:"Водный транспорт",proof:"Подтверждён проектный коридор; точное судоходное расстояние требует трассировки",src:"https://energybase.ru/upstream/gazdobtambey/tenders/epc"},
{a:"bov",b:"tamb",t:"hyp",lab:"проектный коридор — не считать готовым"}];

const COLORS={demand:"#ff9f43",terminal:"#20c7e8",quarry:"#48c774",port:"#4d86ff"},state={origin:null,destination:null,path:null,rates:{rail:null,yrw:null,road:12,water:4,handling:250},rail:{etsng:"231",cargo:"Минерально-строительные материалы",tariffClass:1,cargoCoef:.77,wagonCoef:.909,source:"ФАС №894/25 · ТР №1 (ред. 03.08.2026)"}};
const byId=new Map(POINTS.map(p=>[p.id,p])),adj=new Map(POINTS.map(p=>[p.id,[]])),markers=new Map(),lines=[];
ROUTES.forEach((r,i)=>{r.status=r.status||(r.t==="hyp"?"hypothesis":(r.km&&/^\d/.test(r.km)?"verified":"corridor"));if(r.t!=="hyp"&&r.status!=="hypothesis"&&!(r.a==="kor"&&r.b==="yambst")){adj.get(r.a)?.push([r.b,i]);adj.get(r.b)?.push([r.a,i])}});
const origin=document.querySelector("#origin"),destination=document.querySelector("#destination"),hint=document.querySelector("#hint"),result=document.querySelector("#result"),detail=document.querySelector("#detail");

if(typeof window.L==="undefined"){
  hint.textContent="Карта не загрузилась: недоступна библиотека Leaflet.";
  document.querySelector("#map").innerHTML='<div class="map-error">Картографическая библиотека недоступна.<br>Список карьеров и данные доступны ниже.</div>';
  throw new Error("Leaflet unavailable");
}
const map=L.map("map",{zoomControl:false}).setView([66,72],5);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);L.control.zoom({position:"bottomright"}).addTo(map);

function icon(p){const g=p.group||"";const c=g==="potential"?"#ff7a00":g==="independent"?"#22c55e":g==="nnk"?"#1697ff":g==="altai"?"#a855f7":COLORS[p.c];const txt=g==="nnk"?"ННК":g==="altai"?"АК":"";const size=txt?26:18;return L.divIcon({className:"point-wrap",html:'<div class="map-point '+g+'" style="--c:'+c+'">'+txt+'</div>',iconSize:[size,size],iconAnchor:[size/2,size/2]})}
POINTS.forEach(p=>{const m=L.marker(p.p,{icon:icon(p)}).bindTooltip(p.n,{permanent:true,direction:"top",className:"point-label",offset:[0,-8]});m.on("click",()=>onPoint(p));m.addTo(map);markers.set(p.id,m)});
function style(r){if(r.status==="hypothesis")return{color:"#9a7474",weight:1,dashArray:"3 7",opacity:.2};if(r.t==="road")return{color:"#92765e",weight:1.2,opacity:.3};if(r.t==="water")return{color:"#4b83aa",weight:1.3,opacity:.34};if(r.operator==="yrw")return{color:"#756d8d",weight:1.3,opacity:.36};return{color:"#66757d",weight:1.2,opacity:.32}}
ROUTES.forEach((r,i)=>{const a=byId.get(r.a),b=byId.get(r.b);if(!a||!b)return;const l=L.polyline([a.p,b.p],{...style(r),lineCap:"round",lineJoin:"round",interactive:false}).addTo(map);l.edgeIndex=i;lines.push(l)});
POINTS.filter(p=>p.c==="quarry").forEach(p=>origin.add(new Option(p.n,p.id)));
function reach(id){const seen=new Set([id]),q=[id];while(q.length){const x=q.shift();for(const [y] of adj.get(x)||[])if(!seen.has(y)){seen.add(y);q.push(y)}}return seen}
function setA(id){state.origin=id;state.destination=null;state.path=null;origin.value=id;const rr=reach(id);destination.innerHTML='<option value="">Выберите B</option>';POINTS.filter(p=>p.id!==id&&p.c!=="quarry"&&rr.has(p.id)).forEach(p=>destination.add(new Option(p.n,p.id)));destination.disabled=false;hint.textContent="A выбран. Нажмите на доступную B.";result.hidden=true;render()}
function setB(id){if(!state.origin)return;state.destination=id;destination.value=id;calc()}
function onPoint(p){if(p.c==="quarry")setA(p.id);else if(state.origin&&[...destination.options].some(o=>o.value===p.id))setB(p.id);show(p)}
function show(p){detail.hidden=false;detail.innerHTML='<button class="close">×</button><h2>'+p.n+'</h2><div class="region">'+p.r+'</div><p>'+p.d+'</p><div class="evidence">'+p.m+'</div><div class="role">'+(p.c==="quarry"?"Точка A":state.destination===p.id?"Точка B":"Объект")+'</div><p><a target="_blank" rel="noopener" href="'+p.u+'">Источник ↗</a></p>';detail.querySelector(".close").onclick=()=>detail.hidden=true}
function path(a,b){const q=[a],prev=new Map([[a,null]]),pe=new Map();while(q.length){const x=q.shift();if(x===b)break;for(const [y,i] of adj.get(x)||[])if(!prev.has(y)){prev.set(y,x);pe.set(y,i);q.push(y)}}if(!prev.has(b))return null;let x=b,ids=[],edges=[];while(x!==a){ids.push(x);edges.push(pe.get(x));x=prev.get(x)}ids.push(a);return{ids:ids.reverse(),edges:edges.reverse()}}
function geo(a,b){const A=byId.get(a).p,B=byId.get(b).p,R=6371,d=Math.PI/180,z=Math.sin((B[0]-A[0])*d/2)**2+Math.cos(A[0]*d)*Math.cos(B[0]*d)*Math.sin((B[1]-A[1])*d/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
function dist(r){if(r.km&&/^\d/.test(r.km))return{km:parseFloat(r.km),exact:true};return{km:Math.round(geo(r.a,r.b)*(r.t==="road"?1.22:r.t==="rail"?1.14:r.t==="water"?1.08:1.15)),exact:false}}
function mk(r){return r.operator==="yrw"?"yrw":r.t}function mn(r){return r.operator==="yrw"?"ЯЖДК":r.t==="rail"?"ЖД":r.t==="road"?"Авто":r.t==="water"?"Вода":"Коридор"}
function calc(){const p=path(state.origin,state.destination);if(!p){hint.textContent="Нет рабочего маршрута без гипотез.";return}state.path=p;let km=0,sum=0,est=0,tr=0,last=null;const legs=p.edges.map(i=>{const r=ROUTES[i],d=dist(r),m=mk(r),rate=state.rates[m],priced=Number.isFinite(rate)&&rate>0,c=priced?d.km*rate:0;km+=d.km;if(priced)sum+=c;if(!d.exact)est+=d.km;if(last&&last!==m)tr++;last=m;return{r,d,rate,c,priced}});const hand=tr*state.rates.handling;sum+=hand;const unpriced=legs.filter(x=>!x.priced);result.hidden=false;result.innerHTML='<div class="summary"><div class="kpi"><small>Всего</small><strong>'+(est?"≈ ":"")+Math.round(km)+' км</strong></div><div class="kpi"><small>Доставка</small><strong>'+(unpriced.length?'нужен тариф':'≈ '+Math.round(sum).toLocaleString("ru-RU")+' ₽/т')+'</strong></div><div class="kpi"><small>Эфф. тариф</small><strong>'+(unpriced.length?'—':'≈ '+(sum/km).toFixed(1).replace(".",",")+' ₽/т·км')+'</strong></div></div>'+(unpriced.length?'<div class="handling"><b>Стоимость не рассчитана:</b> для ЖД/ЯЖДК нет подтверждённой ставки. Введите коммерческую ставку вручную либо используйте тарифный расчёт по действующему Тарифному руководству №1.</div>':'')<div class="legs">'+legs.map((x,n)=>'<div class="leg"><div><b>'+(n+1)+'. '+mn(x.r)+' · '+byId.get(x.r.a).n+' → '+byId.get(x.r.b).n+'</b><small>'+(x.d.exact?"заданное":"≈ расчётное")+(x.r.proof?" · "+x.r.proof:"")+'</small></div><div class="money"><b>'+(x.d.exact?"":"≈ ")+x.d.km+' км</b><small>'+x.rate+' ₽/т·км</small><strong>≈ '+Math.round(x.c).toLocaleString("ru-RU")+' ₽/т</strong></div></div>').join("")+'</div>'+(tr?'<div class="handling">Перевалки: '+tr+' × '+state.rates.handling+' = <b>'+hand+' ₽/т</b></div>':'')+'<div class="confidence"><b>Достоверность: '+(est===0?"высокая":est/km<.35?"средняя":"предварительная")+'</b> · расчётных км: '+Math.round(est)+'</div><div class="rates">'+ri("rail","ЖД")+ri("yrw","ЯЖДК")+ri("road","Авто")+ri("water","Вода")+ri("handling","Перевалка")+'</div><div class="note">ЖД/ЯЖДК: ставка по умолчанию удалена. Для коммерческого расчёта нужна подтверждённая ставка/тарифный расчёт. Авто, вода и перевалка пока сценарные. Материал в карьере не включён.</div>';result.querySelectorAll("[data-rate]").forEach(e=>e.onchange=()=>{state.rates[e.dataset.rate]=e.value.trim()===""?null:(+e.value||null);calc()});hint.textContent="Маршрут рассчитан.";render();map.fitBounds(L.latLngBounds(p.ids.map(id=>byId.get(id).p)),{paddingTopLeft:[30,150],paddingBottomRight:[30,260]})}
function ri(k,n){return'<label>'+n+(k==="handling"?" ₽/т":" ₽/т·км")+'<input data-rate="'+k+'" inputmode="decimal" value="'+(state.rates[k]??'')+'" placeholder="'+(k==='rail'||k==='yrw'?'введите ставку':'')+'"></label>'}
function render(){markers.forEach((m,id)=>{const e=m.getElement()?.querySelector(".map-point");if(e){e.classList.toggle("selected-a",id===state.origin);e.classList.remove("available-b")}});if(state.origin){const ok=new Set([...destination.options].map(o=>o.value));markers.forEach((m,id)=>{if(ok.has(id))m.getElement()?.querySelector(".map-point")?.classList.add("available-b")})}lines.forEach(l=>l.setStyle(style(ROUTES[l.edgeIndex])));if(state.path)state.path.edges.forEach(i=>lines.find(l=>l.edgeIndex===i)?.setStyle({color:"#0c668f",weight:4,opacity:.95,dashArray:null}))}
function fit(){map.fitBounds(L.latLngBounds(POINTS.filter(p=>["podg","nyag","laby","ob","kor","bov","tamb"].includes(p.id)).map(p=>p.p)),{paddingTopLeft:[30,140],paddingBottomRight:[30,140]})}
origin.onchange=()=>origin.value&&setA(origin.value);destination.onchange=()=>destination.value&&setB(destination.value);document.querySelector("#fit").onclick=fit;document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));POINTS.forEach(p=>{const m=markers.get(p.id),show=b.dataset.filter==="all"||p.c===b.dataset.filter;if(show&&!map.hasLayer(m))m.addTo(map);if(!show&&map.hasLayer(m))map.removeLayer(m)})});fit();render();